@startuml db_modeling_1 
title 
db_modeling_1
end title

entity 注文 {
    消費税コード(FK)
    注文コード
    --
    顧客名 
    顧客電話番号 
    支払済
}
entity 注文詳細 {
    id
    --
    order_id(FK)
    menu_id(FK)
    quantity
    without_wasabi_count
}
entity {
    menu_id
    --
    name
    amount
}
entity 消費税{
    消費税コード 
    --
    税率 
}

注文 ||--|{ 注文詳細
消費税 ||-||注文  
注文詳細 ||--|| Menus
note right of 注文 : - 金額は算出するものとし永続化しない\n- 顧客データは正規化しない(顧客情報について参照)\n- 支払い前にレコードが作成されることから、tax_id は null 許容とする 
note right of 注文詳細 : - without_wasabi_count はサビぬきの皿数を int 型でカウントする(default:0) 
note right of Menus : - amount は税抜価格

@enduml